services:
  mp-repuestos:
    image: nginx:alpine
    container_name: mp-repuestos-web
    restart: unless-stopped
    ports:
      - "0.0.0.0:8088:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./script.js:/usr/share/nginx/html/script.js:ro
      - ./assets:/usr/share/nginx/html/assets:ro
    networks:
      - default
      - nginx_default

networks:
  nginx_default:
    external: true
